config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :update, :destroy]
  resources :session_participants, only: [:update]
  resources :chatrooms, only: [:show, :index, :new, :create, :destroy] do
    get '/chat_participants/new', to: 'chat_participants#new'
    post '/chat_participants', to: 'chat_participants#create'
    post '/chat_participants/add', to: 'chat_participants#add', as: 'add_chat_participants'
    delete '/chat_participants/:id', to: 'chat_participants#destroy', as: 'delete_chat_participants'
    resources :messages, only: :create
  end

  get '/sessions/choice', to: 'sessions#choice'
  # resources :sessions, except: :destroy
  post '/sessions/fetch', to: 'sessions#fetch'
  # get '/sessions/new', to: 'sessions#new_multi', as: 'new_multi_session'
  # get '/sessions/solo/new', to: 'sessions#new_solo', as: 'new_solo_session'
  post '/sessions', to: 'sessions#create'
  get '/sessions/:id/edit', to: 'sessions#edit', as: 'edit_session'
  patch '/sessions/:id', to: 'sessions#update', as: 'update_session'
  get '/sessions/:id', to: 'sessions#show', as: 'my_session'

  patch '/cover_update', to: 'users#update_cover'
  patch '/avatar_update', to: 'users#update_avatar'
 

end

app/models/chat_participant.rb
class ChatParticipant < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/controllers/chat_participants_controller.rb
class ChatParticipantsController < ApplicationController

  def new
    @chatroom = Chatroom.last
    @chat_participant = ChatParticipant.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @chatrooms = Chatroom.all
    @chatroom = Chatroom.last
    @chatparticipant = ChatParticipant.new
    @chatparticipant.user = @user
    @chatparticipant.chatroom = @chatroom
    @chatparticipant.save!
  end

  def add
    @user = User.find(params[:user_id])
    @chatroom = Chatroom.find(params[:chatroom_id])
    @chatparticipant = ChatParticipant.new
    @chatparticipant.user = @user
    @chatparticipant.chatroom = @chatroom
    @chatparticipant.save!
  end

  def destroy
    @chatroom = Chatroom.find(params[:id])
    @user = current_user
    @chat_participants = ChatParticipant.where(chatroom_id: @chatroom.id)
    @chat_participant = @chat_participants.where(user_id: @user.id)
    @chat_participant.destroy_all
    redirect_to chatrooms_path 
  end
end

app/views/chat_participants/_add_friends.html.erb
<div class="flex-c-c bg-gris-small">
  <div class="pop-up-add">
    <div class="pop-up-add container">
    <% @friends.each do |friend| %>
      <div class="flex-b-c card_invite_chatroom">
        <% if User.find(friend).avatar.attached? %>
          <%= cl_image_tag User.find(friend).avatar.key, width: 120, height: 120, crop: :fill, class: "photo invitation-avatar" %>
        <% else %>
          <%= image_tag "mrlarbin.jpg", alt: "mrlarbin" %>
        <% end %>
        <p class="flex-g-1 p-l-20 nunito"> <%= User.find(friend).first_name %> <%= User.find(friend).last_name %> </p>
        <%= form_tag chatroom_add_chat_participants_path(@chatroom), remote: true do %>
        <%= hidden_field_tag 'user_id', friend%>
        <%= submit_tag 'Inviter', class:"btn-2 invitation-btn" %>
        <% end %>
      </div>
      <% end %>
    </div>
    <%= link_to chatroom_path do %>
      <div class="btn-modale-invit btn-1 cursor border-none">OK</div>
    <%end%>
  </div>
</div>

app/views/chat_participants/_new.html.erb
<div class="flex-c-c bg-gris">
  <div class= "pop-up">
    <% @friends.each do |friend| %>
      <div class="flex-b-c card_invite_chatroom">
        <% if User.find(friend).avatar.attached? %>
          <%= cl_image_tag User.find(friend).avatar.key, width: 120, height: 120, crop: :fill, class: "photo invitation-avatar" %>
        <% else %>
          <%= image_tag "mrlarbin.jpg", alt: "mrlarbin" %>
        <% end %>
        <p class="flex-g-1 p-l-20 nunito"> <%= User.find(friend).first_name %> <%= User.find(friend).last_name %> </p>
          <%= form_tag chatroom_chat_participants_path(@chatroom_for_new_chat_participants), remote: true do %>
          <%= hidden_field_tag 'user_id', friend%>
          <%= submit_tag 'Inviter', class:"btn-2 invitation-btn" %>
          <% end %>
      </div>
        <% end %>
    <%= link_to chatrooms_path do %>
      <div class="btn-modale-invit btn-1 cursor border-none">OK</div>
    <%end%>
  </div>
</div>