config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :update, :destroy]
  resources :session_participants, only: [:update]
  resources :chatrooms, only: [:show, :index, :new, :create, :destroy] do
    get '/chat_participants/new', to: 'chat_participants#new'
    post '/chat_participants', to: 'chat_participants#create'
    post '/chat_participants/add', to: 'chat_participants#add', as: 'add_chat_participants'
    delete '/chat_participants/:id', to: 'chat_participants#destroy', as: 'delete_chat_participants'
    resources :messages, only: :create
  end

  get '/sessions/choice', to: 'sessions#choice'
  # resources :sessions, except: :destroy
  post '/sessions/fetch', to: 'sessions#fetch'
  # get '/sessions/new', to: 'sessions#new_multi', as: 'new_multi_session'
  # get '/sessions/solo/new', to: 'sessions#new_solo', as: 'new_solo_session'
  post '/sessions', to: 'sessions#create'
  get '/sessions/:id/edit', to: 'sessions#edit', as: 'edit_session'
  patch '/sessions/:id', to: 'sessions#update', as: 'update_session'
  get '/sessions/:id', to: 'sessions#show', as: 'my_session'

  patch '/cover_update', to: 'users#update_cover'
  patch '/avatar_update', to: 'users#update_avatar'
 

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :chat_participants, dependent: :destroy
  belongs_to :user
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @chatrooms = Chatroom.all
    @chat_participants = ChatParticipant.all
    @participants = ChatParticipant.where(chatroom_id: @chatroom.id)
    @message = Message.new
    @friendships = current_user.all_friendships
    @friends = @friendships.map { |fs| fs.sender == current_user ? fs.recipient.id : fs.sender.id }
    @chatroom_for_new_chat_participants = Chatroom.last.id
  end

  def index
    @chatrooms = Chatroom.all
    @chat_participants = ChatParticipant.all
    @chatroom = Chatroom.new
    @friendships = current_user.all_friendships
    @friends = @friendships.map { |fs| fs.sender == current_user ? fs.recipient.id : fs.sender.id }
    if @chatrooms.length > 0
      @chatroom_for_new_chat_participants = Chatroom.last.id
    else
      @chatroom_for_new_chat_participants = Chatroom.new(user_id: current_user.id, name: 'default').save!
    end
  end

  # def new
  #   @chatroom = Chatroom.new
  #   @friendships = current_user.all_friendships
  #   @friends = @friendships.map { |fs| fs.sender == current_user ? fs.recipient.id : fs.sender.id }
  # end

  def create
    @chatroom = Chatroom.new
    @chatroom.user = current_user
    @chatroom.name = 'default'
    @chatroom.save
    @current_user = current_user
    @chat_participant = ChatParticipant.new(user_id: @current_user.id, chatroom_id: @chatroom.id)
    @chat_participant.save
  end

  def destroy
    @chatroom = Chatroom.find(params[:id])
    @chatroom.destroy
    redirect_to chatrooms_path
  end

  private

end

app/views/chatrooms/index.html.erb
<%= render "shared/navbar_global" %>

<div class="container-l">
  <div class="flex-b-c container-white-chatroom">
    <div class="container-chatrooms">
      <div class="search-btn-chatroom m-b-20">
        <%= form_tag users_path, method: :get do %>
        <%= text_field_tag :requete,
                          params[:requete],
                          placeholder: "Rechercher des conversations",
                          class: "form-control"
        %>
        <%= submit_tag "Search", class: "btn btn-primary d-none" %>
        <% end %>
      </div>
      <div class="line-chatroom">
      </div>
      <div class="chat-room-container">
      <% if @chatrooms %>
        <% @chatrooms.reverse.each do |chatroom| %>
          <% if chatroom.chat_participants.where(user_id: current_user).exists?%>
            <%= link_to chatroom, class: "flex-b-c chatroom-card" do %>
              <%= cl_image_tag @chat_participants.where(chatroom_id: chatroom.id).last.user.avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo m-r-10" %>
              <div class="flex-g-1 m">
                <div class="flex">
                  <% participants = [] %>
                  <% @chat_participants.where(chatroom_id: chatroom.id).each do |chat_participant| %>
                    <% if chat_participant.user.first_name == current_user.first_name %>
                    <% else %>
                      <% participants << "#{chat_participant.user.first_name}" %>
                    <% end %>
                  <% end %>
                  <% if participants.flatten.join(", ").length > 20 %>
                    <p><%= participants.flatten.join(", ") %> ...</p>
                  <% else %>
                    <p><%= participants.flatten.join(", ") %></p>
                  <% end %>
                </div>
                <% if chatroom.messages.first %>
                  <% if chatroom.messages.last.user == current_user %>
                    <p class="message-chatroom">Vous: <%= chatroom.messages.last.content %></p>
                  <% else %>
                    <p class="message-chatroom"><%= chatroom.messages.last.user.first_name %>: <%= chatroom.messages.last.content %></p>
                  <% end %>
                <% else %>
                <% end %>
              </div>
            <%end%>
          <%end%>
        <%end%>
      <%end%>
      </div>
      <%= form_tag chatrooms_path, remote: true do %>
        <%= hidden_field_tag 'user_id', @chatroom.user %>
        <%= hidden_field_tag 'name', @name %>
        <%= hidden_field_tag 'chat_participants', @chat_participant %>
        <%= submit_tag 'Créer une discussion', class: "flex-c-c btn-1 btn-chatroom cursor border-none"%>
      <% end %>
    </div>
    <div class="show-off">
      <h4 class="blague">Étire toi bien! Tourne 7 fois ta langue dans ta bouche avant de parler.</h4>
    </div>
</div>

<%= render "chat_participants/new" %>

app/views/chatrooms/show.html.erb
<%= render "shared/navbar_global" %>
<div class="container-l">
  <div class="flex-b-c container-white-chatroom">
<!-- INDEX ****************************************************************** -->
    <div class="container-chatrooms">
      <div class="search-btn-chatroom m-b-20">
        <%= form_tag users_path, method: :get do %>
        <%= text_field_tag :requete,
                          params[:requete],
                          placeholder: "Rechercher des conversations",
                          class: "form-control"
        %>
        <%= submit_tag "Search", class: "btn btn-primary d-none" %>
        <% end %>
      </div>
      <div class="line-chatroom">
      </div>
      <div class="chat-room-container">
        <% @chatrooms.reverse.each do |chatroom| %>
          <% if chatroom.chat_participants.where(user_id: current_user).exists?%>
            <%= link_to chatroom, class: "flex-b-c chatroom-card"  do %>
              <%= cl_image_tag @chat_participants.where(chatroom_id: chatroom.id).last.user.avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo m-r-10" %>
              <div class="flex-g-1 elips">
                <div class="flex">
                  <% participants = [] %>
                  <% @chat_participants.where(chatroom_id: chatroom.id).each do |chat_participant| %>
                    <% if chat_participant.user.first_name == current_user.first_name %>
                    <% else %>
                      <% participants << "#{chat_participant.user.first_name}" %>
                    <% end %>
                  <% end %>
                    <p class="long-text-hidden"><%= participants.flatten.join(", ") %></p>
                </div>
                <% if chatroom.messages.first %>
                  <% if chatroom.messages.last.user == current_user %>
                    <p class="message-chatroom long-text-hidden">Vous: <%= chatroom.messages.last.content %></p>
                  <% else %>
                    <p class="message-chatroom long-text-hidden"><%= chatroom.messages.last.user.first_name %>: <%= chatroom.messages.last.content %></p>
                  <% end %>
                <% else %>
                <% end %>
              </div>
            <%end%>
          <%end%>
        <%end%>
      </div>
      <%= form_tag chatrooms_path, remote: true do %>
      <%= hidden_field_tag 'user_id', @chatroom.user %>
      <%= hidden_field_tag 'name', @name %>
      <%= hidden_field_tag 'chat_participants', @chat_participant %>
      <%= submit_tag 'Créer une discussion', class: "flex-c-c btn-1 btn-chatroom cursor border-none"%>
      <% end %>

      <%= render "chat_participants/new"%>
    </div>
<!-- PARTICIPANTS ****************************************************************** -->
    <div class="flex-g-1 p-l-40 container-chatrooms p-r-40" id="messages-container">
      <div class="flex-b-c p-x-15 border-chat">
        <% participants = [] %>
        <% @participants.each do |participant| %>
          <% if participant.user.first_name == current_user.first_name %>
          <% else %>
            <% participants << "#{participant.user.first_name}" %>
            <%= cl_image_tag participant.user.avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo-chat m-r-10" %>
          <% end %>
        <% end %>
        <div class="flex-g-1">
          <h4><%= participants.flatten.join(", ") %></h4>
        </div>
        <div class="icone-small">
          <div class="icone-style" id="add-friends-to-chatroom">
            <i class="fas fa-user-plus"></i>
          </div>
          <div class="nav-item dropdown">
            <div class="icone-style", id="navbarDropdown", data-toggle="dropdown", aria-haspopup="true", aria-expanded="false">
              <i class="fas fa-cogs"></i>
            </div>
            <%if current_user.id == @chatroom.user_id%>
              <div class="dropdown-menu dropdown-menu-right" id="dd-chatroom" aria-labelledby="navbarDropdown">
                  <%= link_to "#", class: "dropdown-item flex-b-c", method: :delete do %>
                    <i class="fas fa-user-edit m-r-10" id="noir"></i>
                    <p class="flex-g-1">Supprimer la discussion</p>
                  <% end %>
            <% else %>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to chatroom_delete_chat_participants_path(@chatroom), class: "dropdown-item flex-b-c", method: :delete do %>
                      <i class="fas fa-user-edit m-r-10" id="noir"></i>
                      <p class="flex-g-1">Quitter la discussion</p>
                    <%end%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      
<!-- MESSAGES ****************************************************************** -->
      <div id="messages" data-chatroom-id="<%= @chatroom.id%>" class="conversation">
        <% @chatroom.messages.reverse.each do |message| %>
          <% if message.user == current_user %>
            <div class="message-container-self" id="messages-<%= message.id%>">
              <i class="author">
                <small><%= message.created_at.strftime("%a %b %e at %l:%M%p")%></small>
              </i>
              <div class="message-content">
                <p><%= message.content %></p>
              </div>
            </div>
          <% else %>
            <div class="message-container-received flex" id="messages-<%= message.id%>">
              <%= cl_image_tag message.user.avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo-message m-r-10" %>
              <div>
                <i class="author">
                  <span><%= message.user.first_name %> -</span>
                  <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
                </i>
                <p><%= message.content %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
<!-- CHAT ****************************************************************** -->
      <div class="content-chat">
        <%= simple_form_for [@chatroom, @message], remote: true do |f| %>
          <%= f.input :content, label: false, placeholder: "Message #" %>
          <%= f.button :submit, value: "Envoyer un message", class: "arrow-left", id: "send" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

<%= render 'chat_participants/add_friends'%>