config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :update, :destroy]
  resources :session_participants, only: [:update]
  resources :chatrooms, only: [:show, :index, :new, :create, :destroy] do
    get '/chat_participants/new', to: 'chat_participants#new'
    post '/chat_participants', to: 'chat_participants#create'
    post '/chat_participants/add', to: 'chat_participants#add', as: 'add_chat_participants'
    delete '/chat_participants/:id', to: 'chat_participants#destroy', as: 'delete_chat_participants'
    resources :messages, only: :create
  end

  get '/sessions/choice', to: 'sessions#choice'
  # resources :sessions, except: :destroy
  post '/sessions/fetch', to: 'sessions#fetch'
  # get '/sessions/new', to: 'sessions#new_multi', as: 'new_multi_session'
  # get '/sessions/solo/new', to: 'sessions#new_solo', as: 'new_solo_session'
  post '/sessions', to: 'sessions#create'
  get '/sessions/:id/edit', to: 'sessions#edit', as: 'edit_session'
  patch '/sessions/:id', to: 'sessions#update', as: 'update_session'
  get '/sessions/:id', to: 'sessions#show', as: 'my_session'

  patch '/cover_update', to: 'users#update_cover'
  patch '/avatar_update', to: 'users#update_avatar'
 

end

app/models/user.rb
require 'twilio-ruby'

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friendships, class_name: 'Friendship', foreign_key: :sender_id
  has_many :recieved_friendships, class_name: 'Friendship', foreign_key: :recipient_id

  has_many :stats, dependent: :destroy
  has_many :session_participants, dependent: :destroy
  has_many :sessions, through: :session_participants, dependent: :destroy
  has_many :sessions, dependent: :destroy
  has_many :chat_participants, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chatrooms, dependent: :destroy

  has_one_attached :avatar
  has_one_attached :cover

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :email, uniqueness: true
  validates :last_name, uniqueness: true


  def regenerate_twilio_token
    # Required for any Twilio Access Token
    account_sid = ENV["ACCOUNT_SID"]
    api_key = ENV["API_KEY_SID"]
    api_secret = ENV["API_KEY_SECRET"]

    # Required for Video
    identity = self.id

    # Create Video grant for our token
    video_grant = Twilio::JWT::AccessToken::VideoGrant.new
    video_grant.room = 'cool room'

    # Create an Access Token
    token = Twilio::JWT::AccessToken.new(
      account_sid,
      api_key,
      api_secret,
      [video_grant],
      identity: identity
    )

    # Generate the token
    self.twilio_token = token.to_jwt
    self.twilio_expire = Time.now.utc + 3000
    self.save
  end

  def read_twilio_token
    regenerate_twilio_token if twilio_token.nil? || Time.now.utc > twilio_expire
    self.twilio_token
  end

  def all_friendships
    [self.friendships.accepted, self.recieved_friendships.accepted].flatten
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @param = params[:param]
    # voir ds session_participants_controller

    if @user == current_user
      @time = 0
      @kcal = 0
      @user.stats.each do |stat|
        @time = @time + stat.time
        @kcal = @kcal + stat.kcal
      end
      @sessions_count = @user.sessions.count
    end

    session_participants = SessionParticipant.where(user: current_user, favorite_status: true)
    @sessions = session_participants.map {|s| s.session}
    @session = Session.new
    @sessions_dates = @user.sessions
                           .map { |session| session.date }
                           .uniq

    @friendships = current_user.all_friendships
    @friends = @friendships.map { |fs| fs.sender == current_user ? fs.recipient.id : fs.sender.id }
    @friend_requests = Friendship.where(recipient_id: current_user.id).where(status: "pending")
  end

  def index
    if params[:requete].present?
      sql_requete = " \
      users.first_name @@ :requete \
      OR users.last_name @@ :requete \
      "
      @users = User.where(sql_requete, requete: "%#{params[:requete]}%")
    else
      @users = User.all
    end
    @self_fdships = current_user.friendships.map(&:id) + current_user.recieved_friendships.map(&:id)

    @users = User.all
    User.all.each do |user|
      @user_fdships = user.friendships.map(&:id) + user.recieved_friendships.map(&:id)
    end
  end

  def update_cover
    @user = current_user
    @user.cover = params[:cover]
    @user.save
  end

  def update_avatar
    @user = current_user
    @user.avatar = params[:avatar]
    @user.save
    render json: { urlImg: Cloudinary::Utils.cloudinary_url(@user.avatar.key)}
    # pour plus de renseignement voir la recherche
    # "How generate a cloudinary URL from the rails controller"
  end
end
# on aurait pu mettre la ligne suivante pour transmettre l'url de l'cl_image_path
# urlIMG: view_context.cl_image_path(@user.avatar.key)}
# mais c'était surtout emplyé à Rails3

app/views/users/_red_counter.html.erb
<% if friend_requests %>
  <div class="red-notif f-c-c">
    <%= friend_requests.count %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render "shared/navbar_global" %>
<div class="container-l container-white">

  <div class="search-btn">
    <%= form_tag users_path, method: :get do %>
    <%= text_field_tag :requete,
                      params[:requete],
                      placeholder: "Rechercher des amis",
                      class: "form-control"
    %>
    <%= submit_tag "Search", class: "btn btn-primary d-none" %>
    <% end %>
  </div>
  <div class="results-search">
    <h2>Résultats pour : <span class="nunito"><%#= params[:requete] %></span></h2>
  </div>

  <div class="user-list-index">
    <% @users.each do |user| %>
      <% if user != current_user %>
        <div class="card-amis" data-recipientuser="<%= user.id %>" data-senderuser="<%= current_user.id %>">
          <div style="width:70%">
            <%= link_to user_path(user) do %>
              <div>
                <% if user.avatar.attached? %>
                  <%= cl_image_tag user.avatar.key %>
                <% else %>
                  <%= image_tag "mrlarbin.jpg", alt: "mrlarbine" %>
                <% end %>
              </div>
              <div>
                <span><%= user.first_name %> <%= user.last_name  %></span>
              </div>
            <% end %>
          </div>
          <div class="flex-c-c width-64">
            <% user_fdships = user.friendships.map(&:id) + user.recieved_friendships.map(&:id) %>
            <% commun = (user_fdships & @self_fdships).first %>
            <% if commun.nil? %>
              <%= form_tag friendships_path, remote: true do %>
                <%= hidden_field_tag 'sender_id', current_user.id  %>
                <%= hidden_field_tag 'recipient_id', user.id  %>
                <%= hidden_field_tag 'status', "pending" %>
                <%= submit_tag "Demander en ami", class: "friend-invitation" %>
              <% end -%>
            <% elsif Friendship.find(commun).status == "pending"%>
              <div class="pending">Demande envoyée</div>
            <% elsif Friendship.find(commun).status == "true"%>
              <div class="we-are-friend">Amis</div>
            <% end  %>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>



  <%#= link_to "Demande d'ami", friendships_path(params: { sender_id: current_user.id, recipient_id: user.id, status:"pending" }), method: :post,remote: true, class: "ask-friend"  %>
<!--   Toutes les friendship ou le user 81  y est
 (User.find(81).friendships).map(&:id)+(User.find(81).recieved_friendships).map(&:id) -->

<!-- Friendship.all.where(status: "pending").destroy_all -->

app/views/users/show.html.erb
<!-- ici 2 manieres differentes pour updater ses images de profils(avatar et cover)
pour la cover, on a un fichier js change_cover.js avec une vue en js.erb
  qui elle va avoir pour fonction d'éviter de recharger la page pour voir la modif
pour l'avatar, on utilise stimulus. POur le coup nous permet de tout faire dans le controlleur pictures_controler.js
 -->

<%= render "shared/navbar_global" %>
<div class="body"></div>
<div class="container-l">
  <div class="banner-user" data-controller="pictures">
    <% if @user.cover.attached? %>
      <%= cl_image_tag @user.cover.key, id: "cover-user" %>
    <% else %>
      <%= image_tag "coverlarbin.jpg", alt: "coverlarbin", id: "cover-user"%>
    <% end %>
    <div class="avatar-user width-100">
      <div class="flex-c-c width-100">
        <% if @user.avatar.attached? %>
        <!-- element que l'on veut updater -->
          <%= cl_image_tag @user.avatar.key,
              id: "avatar-user",
              width: 160, height: 160, crop: :thumb,
              data: { "pictures-target": "avatarUser"} %>
        <% else %>
        <!-- element que l'on veut updater -->
          <%= image_tag "mrlarbin.jpg", alt: "mrlarbin", id: "avatar-user" %>
        <% end %>
        <!-- element ECOUTANT le click -->
        <!-- ici ligne 26 syntaxe pour stimulus version 2 -->
        <div id="avatar-img" data-pictures-target="avatarImg" >
            <i class="fas fa-camera" data-action="click->pictures#choosePicture"></i>
            <!-- element form à submit  -->
            <%= form_with(
              url: avatar_update_path,
              method: "patch",
              class: "hide-form",
              remote: true,
              data: {
                target: "pictures.avatarForm",
                action: "change->pictures#submitForm ajax:success->pictures#majAvatar"
                # on ecoute ici le fait que qd le form est envoyer en est censé avoir une reponse ajax
                # due au remote:true
              }) do |f| %>
              <!-- bouton à ouvrir pour charger le fichier -->
              <%= f.file_field :avatar,
                id: "charge-avatar-file",
                data: { target: "pictures.avatarChargeBtn"} %>
            <% end %>
        </div>
      </div>
    </div>
    <div class="text-cover-home" id="change-cover">
      <div class="flex-b-c">
        <i class="fas fa-camera m-r-10"></i>
        <p class="flex-g-1">Changer la photo de couverture</p>
      </div>
      <div class="hide-form" id="cover-form" >
        <%= form_with( url: cover_update_path, method: "patch", id: "form", remote: true) do |f| %>
          <%= f.file_field :cover , id: "charge-cover-file"%>
        <% end %>
      </div>
    </div>
  </div>
  <div class="name-user">
    <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  </div>




  <!-- ===================================================================== -->
  <!-- =====================   CREATION DES ONGLETS   ====================== -->
  <!--                           // DASHBBOARD //                            -->
  <!-- ===================================================================== -->
  <div class="list-user-profil" >
    <ul class="nav nav-tabs flex-b-c" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= "active" unless params[:tab] == 'ask_friend' %> " id="stat-tab" data-toggle="tab" href="#stat" role="tab" aria-controls="stat" aria-selected="true">STATISTIQUES</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link " id="calendar-tab" data-toggle="tab" href="#calendar" role="tab" aria-controls="calendar" aria-selected="true">CALENDRIER</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= "active" if @param %>" id="sessions-tab" data-toggle="tab" href="#sessions" role="tab" aria-controls="sessions" aria-selected="true">SESSIONS FAVORITES</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link " id="friends-tab" data-toggle="tab" href="#friends" role="tab" aria-controls="friends" aria-selected="true">AMIS</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link <%= "active" if params[:tab] == 'ask_friend' %> " id="en_attente_1-tab" data-toggle="tab" href="#my-friends" role="tab" aria-controls="en_attente_1" aria-selected="true">DEMANDES D'AMIS</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link  " id="en_attente_2-tab" data-toggle="tab" href="#en_attente_2" role="tab" aria-controls="en_attente_2" aria-selected="true">EN ATTENTE 2</a>
      </li>
    </ul>
  </div>
  <!-- ===================================================================== -->
  <!-- =====================   CONTENU DES ONGLETS   ======================= -->
  <!-- ===================================================================== -->
  <div class="container-s container-white m-b-40" >
    <div class="tab-content" id="myTabContent">
      <!-- ================== ONGLET STATISTIQUES ========================== -->
      <div class="tab-pane fade <%= "show active" unless params[:tab] == 'ask_friend' %>" id="stat" role="tabpanel" aria-labelledby="stat-tab">
        <h3 class="roboto">Mes statistiques</h3>
        <div class="flex-b-c m-t-20">
          <div class="stat-card">
            <div class="m-t-15">
              <div>
                <i class="fas fa-fire-alt"></i>
                <div class="stat-card-num ">
                  <div class="flex-c-c">
                    <h3><%= @kcal %></h3>
                  </div>
                </div>
                <p>calories brulées/sem.</p>
              </div>
            </div>
          </div>
          <div class="stat-card">
            <div class="m-t-15">
              <div>
                <i class="fas fa-heartbeat"></i>
                <div class="stat-card-num ">
                  <div class="flex-c-c">
                    <h3><%= @sessions_count %></h3>
                  </div>
                </div>
                <p>sessions realisées/sem.</p>
              </div>
            </div>
          </div>
          <div class="stat-card">
            <div class="m-t-15">
              <div>
                <i class="far fa-clock"></i>
                <div class="stat-card-num ">
                  <div class="flex-c-c">
                    <h3><%= @time %> min</h3>
                  </div>
                </div>
                <p>temps d'activité/sem.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- ================== ONGLET CALENDRIER ============================ -->
      <div class="tab-pane fade" id="calendar" role="tabpanel" aria-labelledby="calendar-tab">
        <div class="container" data-controller="show-sessions">
          <div class="form-wrapper">
            <h3 class="roboto">Mon calendrier</h3>
          </div>
          <div class="container-calendrier">
            <div class="form-wrapper">
              <div id="session-form-div" data-sessions="<%= @sessions_dates.to_json %>">
                <%= label_tag :date, "Mes dates d'entrainement" %>
                <%= text_field_tag :date, "", id: "date"%>
              </div>
            </div>
          </div>
          <div class="card-session-show-user" data-target="show-sessions.card"></div>
        </div>
      </div>
      <!-- ================== ONGLET SESSIONS FAVORITES ==================== -->
      <div class="tab-pane fade <%= "show active" if @param %>" id="sessions" role="tabpanel" aria-labelledby="sessions-tab">
        <h3 class="roboto">Mes sessions favorites</h3>
        <div class="m-t-20">
            <%= render "shared/card_prev_session_show_user", sessions: @sessions%>
        </div>
      </div>

      <!-- ================== ONGLET LISTE AMIS ============================ -->
      <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="friends-tab">
        <div class="flex-b-c flex-wrap deco-none">
          <% @friends.each do |friend| %>
            <div class="card-amis m-t-20">
              <%= link_to user_path(User.find(friend)) do %>
              <div class="flex-b-c">
                <%= cl_image_tag User.find(friend).avatar.key %>
                <div>
                  <p><%= User.find(friend).first_name %></p>
                  <p><%= User.find(friend).last_name  %></p>
                </div>
              </div>
                <div class="ask-friend"><%= link_to "Amis", "/#" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <!-- ================== ONGLET DEMANDE D'AMI ========================= -->
      <div class="tab-pane fade <%= "show active" if params[:tab] == 'ask_friend' %>" id="my-friends" role="tabpanel" aria-labelledby="demande-d-ami-tab">
        <% if Friendship.where(status: "pending").where(recipient_id: current_user.id).empty? %>
          <h4 id="no-invit"> Vous n'avez pas de nouvelle invitation en attente 🙂</h4>
        <% else %>
          <% @friend_requests.each do |friendship| %>
            <%#= render "friendships/demande_d_ami" %>
              <div class="card-invit-to-be-friend">
                <div class="friend-invit-avatar">
                  <%=  cl_image_tag User.find(friendship.sender_id).avatar.key, width: 80, height: 80, radius: "max", crop: "thumb" %>
                </div>
                <div class="friend-invit-id-user-and-button">
                  <h5><%= User.find(friendship.sender_id).first_name %>, <%= User.find(friendship.sender_id).last_name %></h5>
                  <div class="response-to-invit">
                    <%= link_to 'Confirmer', friendship_path(friendship.id), method: :patch, class: "accept button-invit" %>
                    <%= link_to 'Supprimer', friendship_path(friendship.id), method: :delete, class: "refuse button-invit"  %>
                  </div>
                </div>
              </div>
          <% end %>
        <% end %>
      </div>
      <div class="tab-pane fade" id="en_attente_2" role="tabpanel" aria-labelledby="en_attente_2-tab">
        <h3 class="roboto">En Attente 2</h3>
      </div>

    </div>
  </div>
</div>

app/views/users/update_cover.js.erb
const imgCover = document.querySelector('#cover-user');

imgCover.src = "<%= cl_image_path(@user.cover.key) %>";

// ici on a une vue en js.erb