config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :update, :destroy]
  resources :session_participants, only: [:update]
  resources :chatrooms, only: [:show, :index, :new, :create, :destroy] do
    get '/chat_participants/new', to: 'chat_participants#new'
    post '/chat_participants', to: 'chat_participants#create'
    post '/chat_participants/add', to: 'chat_participants#add', as: 'add_chat_participants'
    delete '/chat_participants/:id', to: 'chat_participants#destroy', as: 'delete_chat_participants'
    resources :messages, only: :create
  end

  get '/sessions/choice', to: 'sessions#choice'
  # resources :sessions, except: :destroy
  post '/sessions/fetch', to: 'sessions#fetch'
  # get '/sessions/new', to: 'sessions#new_multi', as: 'new_multi_session'
  # get '/sessions/solo/new', to: 'sessions#new_solo', as: 'new_solo_session'
  post '/sessions', to: 'sessions#create'
  get '/sessions/:id/edit', to: 'sessions#edit', as: 'edit_session'
  patch '/sessions/:id', to: 'sessions#update', as: 'update_session'
  get '/sessions/:id', to: 'sessions#show', as: 'my_session'

  patch '/cover_update', to: 'users#update_cover'
  patch '/avatar_update', to: 'users#update_avatar'
 

end

app/views/shared/_card_body_area.html.erb
<div>
  <div class="card-body-area">
    <div class="white-box">
      <p>Haut du corps</p>
    </div>
  </div>
</div>

app/views/shared/_card_multi_session.html.erb
<div class="card-choice-session multi">
  <div id="multi" class="photo">
    <div class="gradiant-white">
      <h2>COLLECTIVE</h2>
    </div>
  </div>
  <div class="border-violet"></div>
  <div class="bg-blanc flex-b-e p-x-5-0-15-0">
    <div class="flex-g-1 stretch">
      <div class="flex-b-c">
        <i class="fas fa-user-plus"></i>
        <p class="flex-g-1 p-l-10">Invite tes amis</p>
      </div>
      <div class="flex-b-c">
        <i class="far fa-clock"></i>
        <p class="flex-g-1 p-l-10">Renseigne ton temps</p>
      </div>
      <div class="flex-b-c">
        <i class="fas fa-sliders-h"></i>
        <p class="flex-g-1 p-l-10">Renseigne ton niveau</p>
      </div>
      <div class="flex-b-c">
        <i class="fas fa-bullseye"></i>
        <p class="flex-g-1 p-l-10">Renseigne tes objectifs</p>
      </div>
    </div>

      <%= form_tag sessions_path, remote: true do %>
        <%= hidden_field_tag 'user_id', current_user %>
        <%= hidden_field_tag :mode, "multi" %>
        <%= submit_tag "C'EST PARTI", class: "btn-1"%>
      <% end %>
  </div>
</div>

app/views/shared/_card_prev_session.html.erb
<div class="d-flex align-items-center o-x-s">
  <%# raise %>
  <% sessions.each do |session| %>
    <div class="p-r-20">
      <div class="card-prev-session flex-b-c position-relative mr-4">
        <% if BodyArea.find(session.body_area_id).name == "général" %>
          <div class="photo gen">
        <% elsif BodyArea.find(session.body_area_id).name == "haut du corps"%>
          <div class="photo hdc b-p-x">
        <% else %>
          <div class="photo bdc">
        <% end %>
          <div class="gradiant-white"></div>
        </div>
        <div class="content stretch">
          <div>
            <h4><%= BodyArea.find(session.body_area_id).name.capitalize %></h4>
            <div class="flex-b-c">
              <i class="far fa-clock"></i>
              <p class="flex-g-1 p-l-5"><%= session.total_time %> min | <%= translate_date(session.date) %></p>
            </div>
            <div class="flex-b-c w-100-px m-t-4">
              <i class="fas fa-fire-alt"></i>
              <div class="flex-b-c flex-g-1 p-l-8">
                <% if session.difficulty == "débutant" %>
                  <div class="level-bar active"></div>
                  <div class="level-bar"></div>
                  <div class="level-bar"></div>
                  <div class="level-bar"></div>
                <% elsif session.difficulty == "intermédiaire" %>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                  <div class="level-bar"></div>
                  <div class="level-bar"></div>
                <% elsif session.difficulty == "avancé" %>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                  <div class="level-bar"></div>
                <% else %>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                  <div class="level-bar active"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="flex-g-1 right-part">
          <div class="fav">
          <% unless session.session_participants.empty? %>
            <%= simple_form_for session.session_participants.find_by(user: current_user), remote: true do |f| %>
              <%= f.input :favorite_status, value: true, as: :hidden %>
              <%= f.button :button do %>
                 <% if session.session_participants.find_by(user: current_user).favorite_status %>
                  <i class="fas fa-heart fullheart" data-uid="<%= session.id  %>" ></i>
                 <% else %>
                  <i class="far fa-heart" data-uid="<%= session.id  %>" ></i>
                 <% end %>
              <% end %>
            <% end %>
          <% end %>
          </div>
          <div class="cercle-violet-play">
            <div class="posit-relat">
              <i class="fas fa-play"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_card_prev_session_show_user.html.erb
<div class="d-flex align-items-center flex-wrap">
  <% sessions.each do |session| %>
  <div>

    <div class="card-prev-session flex-b-c position-relative m-r-10 m-b-20">
      <% if BodyArea.find(session.body_area_id).name == "général" %>
        <div class="photo gen">
      <% elsif BodyArea.find(session.body_area_id).name == "haut du corps"%>
        <div class="photo hdc b-p-x">
      <% else %>
        <div class="photo bdc">
      <% end %>
        <div class="gradiant-white"></div>
      </div>
      <div class="content stretch">
        <div>
          <h4><%= BodyArea.find(session.body_area_id).name.capitalize %></h4>
          <div class="flex-b-c">
            <i class="far fa-clock"></i>
            <p class="flex-g-1 p-l-5"><%= session.total_time%> min | <%= translate_date(session.date) %></p>
          </div>
          <div class="flex-b-c w-100-px m-t-4">
            <i class="fas fa-fire-alt"></i>
            <div class="flex-b-c flex-g-1 p-l-8">
              <% if session.difficulty == "débutant" %>
                <div class="level-bar active"></div>
                <div class="level-bar"></div>
                <div class="level-bar"></div>
                <div class="level-bar"></div>
              <% elsif session.difficulty == "intermédiaire" %>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
                <div class="level-bar"></div>
                <div class="level-bar"></div>
              <% elsif session.difficulty == "avancé" %>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
                <div class="level-bar"></div>
              <% else %>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
                <div class="level-bar active"></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="flex-g-1 right-part">
        <div class="fav">
          <%= simple_form_for session.session_participants.find_by(user: current_user), remote: true do |f| %>
            <%= f.input :favorite_status, value: true, as: :hidden %>
            <%= f.button :button do %>
               <% if session.session_participants.find_by(user: current_user).favorite_status %>
                <i class="fas fa-heart fullheart" data-uid="<%= session.id  %>" ></i>
               <% else %>
                <i class="far fa-heart" data-uid="<%= session.id  %>" ></i>
               <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="cercle-violet-play">
          <div class="posit-relat">
            <i class="fas fa-play"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_card_solo_session.html.erb
<div class="card-choice-session solo">
  <div id="solo" class="photo">
    <div class="gradiant-white">
      <h2>INDIVIDUELLE</h2>
    </div>
  </div>
  <div class="border-blue"></div>
  <div class="bg-blanc flex-b-e p-x-20">
    <div class="flex-g-1 stretch">
      <div class="flex-b-c">
        <i class="far fa-clock"></i>
        <p class="flex-g-1 p-l-10">Renseigne ton temps</p>
      </div>
      <div class="flex-b-c">
        <i class="fas fa-sliders-h"></i>
        <p class="flex-g-1 p-l-10">Renseigne ton niveau</p>
      </div>
      <div class="flex-b-c">
        <i class="fas fa-bullseye"></i>
        <p class="flex-g-1 p-l-10">Renseigne tes objectifs</p>
      </div>
    </div>
    <%= link_to "C'EST PARTI !", "#", class: "btn-2" %>
  </div>
</div>

app/views/shared/_change_cover.html.erb
<p>hahahahah</p>

app/views/shared/_dropdown_notification.html.erb
<!-- <ul class="dropdown-belt notif-container"> -->
  <% if @friend_requests %>
    <% @friend_requests.each do |friendship| %>
      <%= link_to user_path(current_user.id, tab: "ask_friend"), style: "text-decoration: none" do %>
        <div class="notif-item" data="tobefriend">
          <%= cl_image_tag User.find(friendship.sender_id).avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo"%>
            <span>
              <strong><%= User.find(friendship.sender_id).first_name%></strong>
              <strong><%= User.find(friendship.sender_id).last_name%></strong>
              vous a envoyé une demande d'ami
            </span>
        </div>
      <% end %>
    <% end %>
  <% end %>
<!-- </ul> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar-wellbe.html.erb
<div class="container-l navbar-home">
  <%= link_to root_path do %>
    <%= image_tag "wellbe-police-gourde-blanc.png", class: "logo" %>
  <% end %>
  <div class="flex-g-1">
    <div class="flex-b-c">
      <p class="p-l-40">Nutrition</p>
      <p class="flex-g-1 p-l-20">Blog</p>
    </div>
  </div>
  <% if signed_in? %>
    <div class="icone">
      <!-- ============================================ -->
      <%= link_to current_user, style: "text-decoration: none" do %>
        <% if current_user%>
          <div class="flex-b-c">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag current_user.avatar.key, width: 160, height: 160, crop: :thumb, class: "avatar-photo"%>
            <% else %>
              <%= image_tag "mrlarbin.jpg", alt: "mrlarbin", width: 160, height: 160, crop: :thumb, class: "avatar-photo" %>
            <% end %>
          </div>
        <% else %>
          <% cl_image_tag "lourd.jpg" %>
        <% end %>
      <% end %>
      <!-- ============================================ -->
      <ul class="navbar-nav icone-style home">
        <li id="belt">
          <i class="fas fa-bell"></i>
          <div class="red-notif <%= 'd-none' if @friend_requests&.count < 1 %>">
            <span id="counter"><%= @friend_requests&.count || 0 %></span>
          </div>
          <ul class="dropdown-belt notif-container">
            <%= render "shared/dropdown_notification" %>
          </ul>

        </li>
      </ul>
      <!-- ============================================ -->
      <%= link_to users_path do %>
        <div class="icone-style home">
          <i class="fas fa-user-friends"></i>
        </div>
      <% end %>
      <!-- ============================================ -->
      <%= link_to chatrooms_path do %>
        <div class="icone-style home">
          <i class="fas fa-comments"></i>
        </div>
      <% end %>
      <!-- ============================================ -->
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <div class="icone-style home", id="navbarDropdown", data-toggle="dropdown", aria-haspopup="true", aria-expanded="false">
            <i class="fas fa-tools"></i>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "#", class: "dropdown-item flex-b-c" do %>
              <i class="fas fa-user-edit m-r-10" id="noir"></i>
              <p class="flex-g-1" id="noir">Modifier mon profil</p>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item flex-b-c" do %>
              <i class="fas fa-sign-out-alt m-r-10" id="noir"></i>
              <p class="flex-g-1" id="noir">Déconnexion</p>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
    <%= link_to "CONNEXION", new_user_session_path, class: "btn-3", id: "connexion" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_global.html.erb
<div id="navbar_global">
  <div class="navbar_global">
    <%= link_to root_path do %>
      <%= image_tag "wellbe-police.png", class: "logo" %>
    <% end %>
    <div class="icone">
      <!-- ============================================ -->
      <%= link_to current_user, style: "text-decoration: none" do %>
        <% if current_user.avatar.attached?%>
          <div class="flex-b-c">
            <%= cl_image_tag current_user.avatar.key,
                width: 160, height: 160, crop: :thumb,
                class: "avatar-photo",
                id: "nav-avatar"%>
          </div>
        <% else %>
            <%= image_tag "mrlarbin.jpg", alt: "mrlarbin", width: 160, height: 160, crop: :thumb, class: "avatar-photo" %>
        <% end %>
      <% end %>
      <!-- ============================================ -->
      <ul class="navbar-nav icone-style">
        <li id="belt">
          <i class="fas fa-bell"></i>
          <div class="red-notif <%= 'd-none' if @friend_requests&.count < 1 %>">
            <span id="counter"><%= @friend_requests&.count || 0 %></span>
          </div>
          <ul class="dropdown-belt notif-container">
            <%= render "shared/dropdown_notification" %>
          </ul>
        </li>
      </ul>
      <!-- ============================================ -->
      <%= link_to users_path do %>
        <div class="icone-style">
          <i class="fas fa-user-friends"></i>
        </div>
      <% end %>
      <!-- ============================================ -->
      <%= link_to chatrooms_path do %>
        <div class="icone-style">
          <i class="fas fa-comments"></i>
        </div>
      <% end %>
      <!-- ============================================ -->
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <div class="icone-style", id="navbarDropdown", data-toggle="dropdown", aria-haspopup="true", aria-expanded="false">
            <i class="fas fa-tools"></i>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "#", class: "dropdown-item flex-b-c" do %>
              <i class="fas fa-user-edit m-r-10" id="noir"></i>
              <p class="flex-g-1">Modifier mon profil</p>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item flex-b-c" do %>
              <i class="fas fa-sign-out-alt m-r-10" id="noir"></i>
              <p class="flex-g-1">Déconnexion</p>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="trace-gradiant"></div>
</div>

app/views/shared/_pop_up_session.html.erb
<div class="flex-c-c bg-gris">
  <div class="pop-up">
    <div class="cross">
      <i class="fas fa-times"></i>
    </div>
    <%= image_tag "session-show/popup.jpg", class: "pop-up-photo"%>
    <div class="trace-gradiant"></div>
    <div class="pop-up-content">
      <h1>FÉLICITATIONS !</h1>
      <div class="pop-up-stat flex-c-c">
        <div>
          <i class="fas fa-fire-alt"></i>
          <h3>80 kcal</h3>
        </div>
      </div>
      <div class="flex-c-c">
        <%= link_to "Voir mes statistiques", user_path(current_user), class: "btn-1" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_red_notif.html.erb
<div>
  bla
</div>